### PR TITLE
Monorepo

### PR DESCRIPTION
**Pull request by michaelfig**
Refs #47 

Forms a basis for the new `lib-jessie` library.

### CODE REVIEW

**Comment by dckc** [comment]
maintaining harden separately? care to elaborate on why?

**Comment by michaelfig** [comment]
> maintaining harden separately? care to elaborate on why?

I'm not looking for reviews yet. :wink:

But to elaborate, I'm thinking that harden may move from SES to Jessie (from OS to kernel), and then SES can depend on some of the Jessie machinery.  I haven't fully justified this yet, but further discussion will be had before attempting to land this.

**Comment by erights** [comment]
Given that Jessie is a separate monorepo and local-Jessie is a subset of SES, it makes sense that anything common to both local-Jessie and SES, like `harden`, be in Jessie and depended upon by SES. I think this would be a good move.

**Comment by michaelfig** [comment]
We'll take this in smaller pieces.

**Pull request closed without merging**
